# -*- coding: utf-8 -*-
"""Création de fonction mathématique simple .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kew5qR9DuAHdfFldpHEi-Y4ZsZQS_qWm

# **Création de fonction mathématique simple en Python**

## **Implémentation de la fonction polynomiale**
"""

# définition de la fonction polynomiale sous le nom de f(x)
def f(x):
  x = (x**3) - 1.5*(x**2)-6*x+5
  return (x)

# test du code 
f(5)

"""## **Implémentation de la fonction factorielle**"""

# définition de la fonction factorielle par une approche récursive 
def factorielle(n):
  if n == 0 :
      return 1
  else :
      return n * factorielle(n-1)

# test du code 
factorielle(5)

# test du code avec 0
factorielle(0)

"""## **Implémentation de la suite de Fibonnaci**"""

# Définition de la fonction suite de Fibonnaci 
# Avec implantation d'une saisie de donnée par l'utilisateur directement dans la fonction
def Fibonnaci():
  nterms = int(input("Entrez un nombre: "))
 
  n1 = 0
  n2 = 1
 
  print("la suite fibonacci est :")
  print(n1, ",", n2, end=", ")
 
  for i in range(2, nterms):
    suivant = n1 + n2
    print(suivant, end=", ")
 
    n1 = n2
    n2 = suivant

Fibonnaci()

"""### **Fin 1e partie**



"""

